-- Enables UUID extension if not already active
-- Although v7 is generated by the app, v4 may be useful.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Departments Table
-- Note that `manager_id` and `parent_department_id` are initially null
-- to allow insertion and avoid circular dependency during creation.
CREATE TABLE departments (
                             id UUID PRIMARY KEY,
                             name VARCHAR(255) NOT NULL,
                             manager_id UUID,
                             parent_department_id UUID,

                             created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                             updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                             deleted_at TIMESTAMPTZ,

                             CONSTRAINT fk_parent_dept
                                 FOREIGN KEY(parent_department_id)
                                     REFERENCES departments(id)
                                     ON DELETE SET NULL
);

-- Employees Table
CREATE TABLE employees (
                           id UUID PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           cpf VARCHAR(11) NOT NULL,
                           rg VARCHAR(20),
                           department_id UUID NOT NULL,

                           created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                           updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                           deleted_at TIMESTAMPTZ,

    -- Uniqueness Constraints
                           CONSTRAINT uq_cpf UNIQUE(cpf),
                           CONSTRAINT uq_rg UNIQUE(rg), -- Allows multiple nulls, but unique if provided

    -- Foreign Key to Department
                           CONSTRAINT fk_employee_dept
                               FOREIGN KEY(department_id)
                                   REFERENCES departments(id)
                                   ON DELETE RESTRICT -- Prevents deleting dept with employees
);

-- Adds Manager Foreign Key (circular)
-- The manager is an employee. If the manager is terminated (deleted),
-- the department is left without a manager (SET NULL).
ALTER TABLE departments
    ADD CONSTRAINT fk_dept_manager
        FOREIGN KEY(manager_id)
            REFERENCES employees(id)
            ON DELETE SET NULL;

-- Indexes for search optimization
CREATE INDEX idx_employee_dept_id ON employees(department_id);
CREATE INDEX idx_employee_cpf ON employees(cpf);
CREATE INDEX idx_dept_parent_id ON departments(parent_department_id);
CREATE INDEX idx_dept_manager_id ON departments(manager_id);

-- Constraint para garantir que o RG, se não for nulo, é único
-- A constraint UNIQUE(rg) já faz isso, mas isso é mais explícito
-- para algumas versões de PG. A de cima é suficiente.
-- CREATE UNIQUE INDEX idx_rg_not_null ON colaboradores(rg) WHERE rg IS NOT NULL;
